### ISSUE TITLE
文件是需要自己创建吗？

### ISSUE THREAD

**Issue by woxiangshuo** [fei-ke/HmsPushZygisk#1]
data/misc/hms/app.conf这个文件是需要自己创建吗？安装完模块手后目录内没有hms文件夹，magisk alpha 27006，这样可以吗？[
![Screenshot_20240801-184128_MT管理器](https://github.com/user-attachments/assets/1215f43f-8f51-486e-bca9-b6d1e424de70)
](url)

**Comment by fei-ke** [comment]
需要手动创建
